### ISSUE TITLE
Run locally on docker failing

### ISSUE THREAD

**Issue by louisaslett** [rocker-org/binder#45]
I'm pretty new to Binder, so I hope this isn't a false positive issue report (apologies in advance if so).

Per the documentation in the README, I'm trying to play round with this on my local machine Docker, but on `rocker/binder:latest` and `rocker/binder:4.1.0` I get:

```
# docker run -p 8888:8888 rocker/binder:4.1.0
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jupyter_core/command.py", line 285, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/lib/python3.8/dist-packages/jupyter_core/command.py", line 124, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-notebook` not found.
```

However, if I go back far enough, it works just fine:

```
# docker run -p 8888:8888 rocker/binder:3.6.2
[I 10:57:42.022 NotebookApp] Writing notebook server cookie secret to /home/rstudio/.local/share/jupyter/runtime/notebook_cookie_secret
[I 10:57:42.535 NotebookApp] Serving notebooks from local directory: /home/rstudio
[I 10:57:42.535 NotebookApp] The Jupyter Notebook is running at:
[I 10:57:42.535 NotebookApp] http://b439f1838a83:8888/?token=fc2430c9b88a67d70183a44e61fd0c6d382c5d93abe46dab
[I 10:57:42.535 NotebookApp]  or http://127.0.0.1:8888/?token=fc2430c9b88a67d70183a44e61fd0c6d382c5d93abe46dab
[I 10:57:42.535 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 10:57:42.539 NotebookApp] No web browser found: could not locate runnable browser.
[C 10:57:42.539 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/rstudio/.local/share/jupyter/runtime/nbserver-8-open.html
    Or copy and paste one of these URLs:
        http://b439f1838a83:8888/?token=fc2430c9b88a67d70183a44e61fd0c6d382c5d93abe46dab
     or http://127.0.0.1:8888/?token=fc2430c9b88a67d70183a44e61fd0c6d382c5d93abe46dab
```

I don't know if this is related to #44 or not, hence opening as a new issue, but these maybe need to be merged if they are different symptoms of the same issue.

Thanks,

Louis

**Comment by louisaslett** [comment]
My apologies, I've just realised that this is the old repository and there is a live issue about the same problem (in the correct repo!) here: rocker-org/rocker-versioned2#147

Closing this now.
